version: '2.1'

services:
  messenger-db-node:
    build:
      context: mariadb
      dockerfile: Dockerfile
    container_name: messenger-db-node
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: msgdb
      MYSQL_USER: msguser
      MYSQL_PASSWORD: msguser
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    networks:
      - msg-network
    ports:
      - 3360:3306
    healthcheck:
      test: "/usr/bin/mysql --user=msguser --password=msguser --execute \"SHOW DATABASES;\""
      timeout: 20s
      retries: 5
    volumes:
      - msg-db-node-data:/var/lib/mysql

  user_service:
    build:
      context: UserService
      dockerfile: Dockerfile
    container_name: user_service
    environment:
      - DB_HOST=messenger-db-node
      - DB_PORT=3306
      - DB_LOGIN=msguser
      - DB_PASSWORD=msguser
      - DB_DATABASE=msgdb
    ports:
      - 8080:8080
    networks:
      - msg-network
    depends_on:
      messenger-db-node:
        condition: service_healthy

  group_service:
    build:
      context: GroupService
      dockerfile: Dockerfile
    container_name: group_service
    environment:
      - SERVICE_HOST=user_service
      - DB_HOST=messenger-db-node
      - DB_PORT=3306
      - DB_LOGIN=msguser
      - DB_PASSWORD=msguser
      - DB_DATABASE=msgdb
    ports:
      - 8081:8081
    networks:
      - msg-network
    depends_on:
      user_service:
        condition: service_started

  p2p_service:
    build:
      context: P2PService
      dockerfile: Dockerfile
    container_name: p2p_service
    environment:
      - SERVICE_HOST=user_service
      - DB_HOST=messenger-db-node
      - DB_PORT=3306
      - DB_LOGIN=msguser
      - DB_PASSWORD=msguser
      - DB_DATABASE=msgdb
    ports:
      - 8082:8082
    networks:
      - msg-network
    depends_on:
      user_service:
        condition: service_started

volumes:
  msg-db-node-data:

networks:
  msg-network:
    driver: "bridge"
    external: false